/* Copyright (c) The Grit Game Engine authors 2016
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <perf_trace.h>

enum GritTracePoint {
    TRACE_FRAME_BEGIN,
    TRACE_GAME_LOGIC_BEGIN,
    TRACE_GAME_LOGIC_END,
    TRACE_PHYSICS_BEGIN,
    TRACE_PHYSICS_COLLISION_BEGIN,
    TRACE_PHYSICS_COLLISION_END,
    TRACE_PHYSICS_RESOLUTION_BEGIN,
    TRACE_PHYSICS_RESOLUTION_END,
    TRACE_PHYSICS_DYNAMICS_BEGIN,
    TRACE_PHYSICS_DYNAMICS_END,
    TRACE_PHYSICS_END,
    TRACE_ANIMATION_BEGIN,
    TRACE_ANIMATION_END,
    TRACE_SHADOW_CAST1_BEGIN,
    TRACE_SHADOW_CAST1_FRUSTUM_CULL_BEGIN,
    TRACE_SHADOW_CAST1_FRUSTUM_CULL_END,
    TRACE_SHADOW_CAST1_DRAW_BEGIN,
    TRACE_SHADOW_CAST1_DRAW_END,
    TRACE_SHADOW_CAST1_END,
    TRACE_SHADOW_CAST2_BEGIN,
    TRACE_SHADOW_CAST2_FRUSTUM_CULL_BEGIN,
    TRACE_SHADOW_CAST2_FRUSTUM_CULL_END,
    TRACE_SHADOW_CAST2_DRAW_BEGIN,
    TRACE_SHADOW_CAST2_DRAW_END,
    TRACE_SHADOW_CAST2_END,
    TRACE_SHADOW_CAST3_BEGIN,
    TRACE_SHADOW_CAST3_FRUSTUM_CULL_BEGIN,
    TRACE_SHADOW_CAST3_FRUSTUM_CULL_END,
    TRACE_SHADOW_CAST3_DRAW_BEGIN,
    TRACE_SHADOW_CAST3_DRAW_END,
    TRACE_SHADOW_CAST3_END,
    TRACE_FRAME_FRUSTUM_CULL_BEGIN,
    TRACE_FRAME_FRUSTUM_CULL_END,
    TRACE_FRAME_FRUSTUM_GBUFFER_DRAW_BEGIN,
    TRACE_FRAME_FRUSTUM_GBUFFER_DRAW_END,
    TRACE_FRAME_FRUSTUM_ALPHA_DRAW_BEGIN,
    TRACE_FRAME_FRUSTUM_ALPHA_DRAW_END,
    TRACE_FRAME_SYNC,
    TRACE_FRAME_END,

    TRACE_FRAME_SIZE, // Must be the last enumerator.
};

FrameTraceBuffer<TRACE_FRAME_SIZE> trace_buf();
